#!/zhome/ee/d/137643/Desktop/Test/project-env/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from dtu.scripts import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
